# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: beneaththeink/node-xvfb
      # - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      # - image: aheuermann/electron
      # - image: eruvanos/xvfb
      # - image: comiq/xvfb
      # 'export DISPLAY=:9.0 && Xvfb -ac -screen scrn 1024x768x24 :9.0 &' version
      # - image: beneaththeink/node-xvfb
      # - image: markadams/chromium-xvfb
      # - image: otamachan/xvfb
      # - image: bdadamas24/node-xvfb

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test
      # - run: apt-get update && apt-get install -y xvfb x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps clang libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib

      # - run: HEADLESS=0 yarn test

      # - run: echo $DISPLAY
      # - run: export DISPLAY=:99.0
      # - run: echo $DISPLAY
      # - run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      # - run: yarn test

      - run: xvfb-run --server-args="-screen 0 1024x768x24" yarn test
      # - run: make test